os:
  - linux
  - osx
language: 
  - python
python:
  - "2.4"
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
install:
  - cs test-ci
  - pip3 install pytest
script:
  - py.test model.py
